### ISSUE TITLE
Remove use of popt

### ISSUE THREAD

**Issue by rossburton** [rhboot/efibootmgr#114]
Like efivar, it would be nice if `popt` was replaced with `getopt_long`, as popt is very old and unmaintained.

**Comment by rbisewski** [comment]
I think I like this idea. The last major revision of popt, v1.16, was released in 2010, and mostly only very minor tweaks since it looks unmaintained; confer the Debian revision history [here](https://salsa.debian.org/debian/popt).

Probably [gengetopt](https://www.gnu.org/software/gengetopt/gengetopt.html) could be used to recreate the argument parser in `getopt_long` style. Right now in this repo, I believe the following files depend on popt:

* src/eficonman.c
* src/efibootnext.c
* src/efibootdump.c

If anyone is interested in doing this, I think smaller diffs might be good, so I think maybe there should be 3 tickets and separate PR branches for each file, so that this could be tested better.

Peter Jones, if nobody gets around to this, I could probably do it at some point :)

**Comment by vathpela** [comment]
In general I hate getopt and popt is much nicer, but its maintenance has certainly suffered for quite some time.  I'll be happy to review some PRs.

**Comment by tpgxyz** [comment]
popt-1.18 has been released couple days ago, so it is not dead :)
https://github.com/rpm-software-management/popt

**Comment by rossburton** [comment]
😮

**Comment by rbisewski** [comment]
I didn't think would ever happen, I figured popt was dead, but it does look like there is a new release.

Well, I suppose we could leave popt in the efibootmgr since that seems to be the crux of this issue.

Did you perhaps want to close the issue rossburton? Or did you have other concerns with popt?

**Comment by rossburton** [comment]
Less dependencies are good, but the primary reason for dropping popt was that it was unmaintained thus hard to get through legal approval to release. So I'm happy either way.

**Comment by martinezjavier** [comment]
I guess we can close this issue since `popt` doesn't seem to be unmaintained anymore, which was the rationale for asking the change? If someone is willing to write a patch, @vathpela said that will be happy to review it.
