### ISSUE TITLE
efibootmgr -d unintuintive behavior

### ISSUE THREAD

**Issue by quixotrykd** [rhboot/efibootmgr#117]
When running `efibootmgr` with the `-b` flag, a drive is expected. If the user passes a partition instead, `efibootmgr` will silently use the drive on which that partition resides. 

We should either force the user to enter a disk device by an explicit failure when a partition is specified, or at least warn the user that the partition to which the added entry refers to is not what they may expect.

For instance: running `efibootmgr -c -d /dev/sda2 -l "\EFI\boot\EFI\grub.efi"` will use the (implicitly specified) first partition on `/dev/sda`, `/dev/sda1`, for the new entry. This appears to be in direct conflict with what the user specifies, although it is a result of the implicit use of the first partition. There should be some sort of warning/failure presented to the user in this case.

**Comment by vathpela** [comment]
I think this is just an error in `libefivar`; originally `efibootmgr` expected `-d /dev/sda -p 2` but just assumed `-p 1` if `-p` was omitted or if `-d /dev/sda1` was specified, and generally this works because most people use the first partition.  At some point I recognized that nearly everyone (including me) thought `-d` took a partition, so I added parsing to `libefivar` for that.  So I think this is just en `libefivar` bug.

We've fixed a couple of those, so see if it's still an issue.  If it is, please open an issue over at https://github.com/rhboot/efivar/issues with a log from the most recent `efivar` and `efibootmgr`, and invokes efibootmgr as `efibootmgr -c -d /dev/sda2 -l "\EFI\boot\EFI\grub.efi" -v 3`, that would be really helpful.

**Comment by martinezjavier** [comment]
Closing this since the issue if still present would be in `libefivar` as mentioned by @vathpela. Feel free to file an issue there is you are still experiencing this problem.
