### ISSUE TITLE
Handle debris in efibootmgr -v output

### ISSUE THREAD

**Issue by mrmazda** [rhboot/efibootmgr#123]
Results like the following occur on Asus and Gigabyte systems here (what follows is from the Asus with AMI version 1402, booted to Tumbleweed):

# efibootmgr -v
BootCurrent: 0000
Timeout: 1 seconds
BootOrder: 0000,0004,0005,0003
Boot0000* opensusetw    HD(1,GPT,5b331d7f-9488-4df5-9eed-c7250696b833,0x800,0xa0000)/File(\EFI\OPENSUSETW\GRUBX64.EFI)
Boot0003* CD/DVD Drive  BBS(CDROM,,0x0)..GO..NO........u.O.p.t.i.a.r.c. .D.V.D. .R.W. .A.D.-.7.2.0.0.S....................A...........................D..Gd-.;.A..MQ..L.O.p.t.i.a.r.c. .D.V.D. .R.W. .A.D.-.7.2.0.0.S........BO
Boot0004* UEFI OS       HD(1,GPT,5b331d7f-9488-4df5-9eed-c7250696b833,0x800,0xa0000)/File(\EFI\BOOT\BOOTX64.EFI)..BO
Boot0005* Hard Drive    BBS(HD,,0x0)..GO..NO........o.M.K.N.S.S.D.S.R.1.2.0.G.B....................A...........................>..Gd-.;.A..MQ..L.B.M.8.1.4.0.1.2.0.1.3.0.D.D.B.8. .4. . ........BO

Expected output should look more like the following:
# efibootmgr -v
BootCurrent: 0000
Timeout: 1 seconds
BootOrder: 0000,0004,0005,0003
Boot0000* opensusetw	HD(1,GPT,5b331d7f-9488-4df5-9eed-c7250696b833,0x800,0xa0000)/File(\EFI\OPENSUSETW\GRUBX64.EFI)
Boot0003* CD/DVD Drive	BBS(CDROM,,0x0)
Boot0004* UEFI OS	HD(1,GPT,5b331d7f-9488-4df5-9eed-c7250696b833,0x800,0xa0000)/File(\EFI\BOOT\BOOTX64.EFI)
Boot0005* Hard Drive	BBS(HD,,0x0)

On both the Asus and the Gigabyte the following are installed, all in UEFI mode (with each's respective GRUB_DISTRIBUTOR):
openSUSE Tumbleweed (opensusetw)
openSUSE 15.2A (no such file /etc/default/grub)
openSUSE 15.1 (opensuse151)
openSUSE 15.0 (opensuse150)
Debian 10 Buster (debian10)
Ubuntu 18.04 (tubuntu)
Fedora 31 (no such file /etc/default/grub) (Asus only)
Mint 19.4 (no such file /etc/default/grub) (Asus only)

On each, opensuseTW is the expected Boot0000 entry, as it was the first installed OS on both, and it is the only OS on which the ESP is normally mounted while it is booted. Most modifications to firmware using efibootmgr have been made while booted to Tumbleweed.

**Comment by esteelpaz** [comment]
Thanks to mrmazda for starting this bug report, which might be because of my recent experience with a fresh install of TW into a multi-boot '12 Mac Pro . . . after logging in to the system after install on cold boot grub will not load the TW install, but will load two ubuntu based installs, a Gecko rolling, and a Manjaro install . . . only TW remains not bootable via Grub.  Recently got it to boot using SuperGrub2 disk, otherwise, nope.

https://forums.opensuse.org/showthread.php/538216-Install-followed-by-fresh-upgrade-couple-days-later-lost-by-grub-EFI-boot?p=2921239#post2921239

**Comment by vathpela** [comment]
These aren't /wrong/, but perhaps there's a better way to display them.  What's going on here is your system firmware is creating boot entries with optional loader data (which is basically the bootloader command line options) in a binary format, and we can't display them reasonably.  Right now we're testing isprint(x) and printing "." when it isn't.

Possibly the right thing to do is check if "x !=0 && !isprint(x)" is true for any byte in them, and if so dump the hex of the optional loader data instead of deciding on a character by character basis.

**Comment by frozencemetery** [comment]
This went in in def4bebd6cf335236c7ad3c6be3299aa444b83fc
